/** Audit log strings. English placeholder copy, like the rest of the panel. */
export const auditCopy = {
  intro:
    'Every admin action, newest first: who did what to which record, why, and what changed. The log is append-only.',
  filters: {
    title: 'Filters',
    actorId: 'Admin id',
    action: 'Action (prefix)',
    actionHint: 'For example "catalogue" or "master.verify".',
    targetType: 'Target type',
    targetTypeHint: 'For example "service" or "order".',
    targetId: 'Target id',
    from: 'From',
    to: 'To',
    apply: 'Apply filters',
    clear: 'Clear',
    invalidId: 'Paste a full id (a UUID).',
    invalidAction: 'Lower-case words separated by dots.',
    invalidTargetType: 'A lower-case word, underscores allowed.',
    targetIdNeedsType: 'A target id needs its target type.',
    invalidRange: '"From" must be before "To".',
  },

  table: {
    caption: 'Audit log',
    when: 'When',
    actor: 'Admin',
    action: 'Action',
    target: 'Target',
    reason: 'Reason',
    changes: 'Changes',
    noReason: '—',
    show: 'Show changes',
    hide: 'Hide changes',
    showFor: (action: string) => `Show changes for ${action}`,
    hideFor: (action: string) => `Hide changes for ${action}`,
    field: 'Field',
    before: 'Before',
    after: 'After',
    absent: '—',
    noChanges: 'Nothing changed — this entry records a read.',
    diffCaption: (action: string) => `Changes made by ${action}`,
  },

  loading: 'Loading the audit log…',
  loadFailed: 'The audit log could not be loaded.',
  retry: 'Try again',
  empty: 'No entries match these filters.',
  loadMore: 'Load more',
  loadingMore: 'Loading…',
} as const;
