/** The catalogue editor's strings. English placeholder copy, like the rest of the panel. */
export const catalogueCopy = {
  intro:
    'Categories and services as the apps show them, inactive ones included. A reference price is what the app shows before a master quotes; masters still set their own.',
  loading: 'Loading the catalogue…',
  loadFailed: 'The catalogue could not be loaded.',
  retry: 'Try again',
  empty: 'The catalogue has no categories yet.',
  newCategory: 'New category',
  newService: 'Add service',
  noServices: 'No services in this category yet.',

  active: 'Active',
  inactive: 'Inactive',
  activate: 'Activate',
  deactivate: 'Deactivate',
  edit: 'Edit',
  moveUp: (name: string) => `Move ${name} up`,
  moveDown: (name: string) => `Move ${name} down`,
  up: '↑',
  down: '↓',
  actionFailed: 'That change was not saved. Try again.',

  columns: {
    name: 'Name',
    pricing: 'Pricing',
    price: 'Reference price',
    status: 'Status',
    actions: 'Actions',
  },
  pricing: {
    fixed: 'Fixed',
    inspection: 'Inspection',
  },
  noPrice: '—',

  form: {
    createCategoryTitle: 'New category',
    editCategoryTitle: 'Edit category',
    createServiceTitle: 'New service',
    editServiceTitle: 'Edit service',
    slug: 'Slug',
    slugHint: 'Lower-case letters, digits and single hyphens. Used in links; change it rarely.',
    nameAz: 'Name (Azerbaijani)',
    nameEn: 'Name (English, optional)',
    nameRu: 'Name (Russian, optional)',
    displayOrder: 'Display order (optional)',
    displayOrderHint: 'Lower comes first. The arrows on the list are usually easier.',
    active: 'Active — shown in the apps',
    category: 'Category',
    pricingKind: 'Pricing',
    pricingFixed: 'Fixed reference price',
    pricingInspection: 'Price set after inspection',
    price: 'Reference price (AZN)',
    priceHint: 'For example 45 or 45.50.',
    priceNotApplicable: 'An inspection-priced service has no reference price.',
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',

    slugInvalid: 'Use lower-case letters, digits and single hyphens, at most 64 characters.',
    slugTaken: 'This slug is already used by another category or service. Choose another.',
    nameAzRequired: 'An Azerbaijani name is required.',
    nameTooLong: 'At most 80 characters.',
    nameInvalid: 'Check the names: Azerbaijani is required and each is at most 80 characters.',
    displayOrderInvalid: 'A whole number from 0 to 1,000,000.',
    priceRequired: 'A fixed-price service needs a reference price.',
    priceFormat: 'Enter an amount like 45 or 45.50.',
    priceRange: 'Between 0.01 and 100,000 AZN.',
    categoryInvalid: 'Choose a category.',
    rejected: 'The server did not accept this. Check the fields and try again.',
    unexpected: 'Something went wrong. Try again.',
  },
} as const;
