import { relations, sql } from 'drizzle-orm';
import { check, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

import { users } from './users';

/**
 * The customer **role profile** — what a person is called and looks like when
 * they order work — hanging off the account that actually authenticates
 * (`docs/product/user-roles.md`: "`customers` and `masters` are role profiles
 * referencing `users`").
 *
 * Nothing about identity is repeated here. The phone number stays on `users`,
 * because a person with both roles has one number and two profiles, and a
 * copy on each would be two rows to keep in step and two places for support to
 * change the wrong one. The same goes for account status: a suspension is a
 * property of the account, not of one of its faces.
 *
 * Ids are UUIDv7 generated by the application (`common/ids/uuid-v7.ts`), as on
 * every other table — no column carries a database default, so the one
 * generator stays the one generator.
 */
export const customers = pgTable(
  'customers',
  {
    id: uuid('id').primaryKey(),

    /**
     * RESTRICT rather than CASCADE, the default across this schema
     * (`docs/architecture/database-architecture.md` § Integrity rules).
     * Users are soft-deleted, so this never fires in normal operation; if it
     * ever does, failing loudly is the point.
     */
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),

    displayName: text('display_name').notNull(),

    /**
     * Object-storage key, never a URL and never client-supplied
     * ([ADR-0005](docs/decisions/ADR-0005-object-storage.md): "Keys are
     * server-generated UUIDs, never client-supplied filenames").
     *
     * Nothing writes it yet — the presigned-upload flow waits on the storage
     * provider ADR-0005 leaves open — and no endpoint accepts it, precisely so
     * a client cannot point its avatar at a key it does not own.
     */
    avatarKey: text('avatar_key'),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),

    /**
     * Soft delete. A hard delete would orphan the orders, payments and reviews
     * that must stay accountable (`docs/product/user-roles.md`), and those
     * reference the customer, not the user.
     */
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (table) => [
    /**
     * Unique across **all** rows, not only live ones — deliberately unlike
     * `users_phone_e164_live_unique`.
     *
     * The partial index on `users` exists because a phone number can be
     * reassigned to a different person, so a dead row must not block a new
     * account. A user id cannot be reassigned: the same account coming back
     * is the same person, and the only sensible answer to "create my customer
     * profile again" is to hand back the profile they already had, with its
     * order history still pointing at it. A partial index would instead let
     * that request insert a second row and silently strand the first — the
     * history would survive, attached to a profile nobody can reach.
     *
     * So the revival path is an UPDATE clearing `deleted_at`
     * (`CustomersRepository.createOrRevive`), and this index is what makes
     * that the only possible outcome rather than the one the application
     * happens to take.
     */
    uniqueIndex('customers_user_id_unique').on(table.userId),

    /**
     * The same bound the Zod schema applies at the API boundary, restated
     * where it cannot be bypassed. Validation runs on the request path only;
     * a seed script, a migration or a future admin tool writes straight to the
     * table, and "constraints belong in the database — application-level
     * checks race; database constraints do not"
     * (`docs/architecture/database-architecture.md`).
     *
     * `btrim` because a name of eighty spaces is an empty name wearing a
     * costume, and `length` counts characters rather than bytes, so an
     * Azerbaijani name is not shorter for containing an ə.
     */
    check(
      'customers_display_name_length',
      sql`length(btrim(${table.displayName})) between 1 and 80`,
    ),
  ],
);

export const customersRelations = relations(customers, ({ one }) => ({
  user: one(users, { fields: [customers.userId], references: [users.id] }),
}));

export type CustomerRow = typeof customers.$inferSelect;
export type NewCustomerRow = typeof customers.$inferInsert;
