import { relations, sql } from 'drizzle-orm';
import {
  index,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

/**
 * Account state, from `docs/product/user-roles.md` § Account states.
 *
 * Only the three states that belong to the *account* are here.
 * `pending_verification`, `changes_requested` and `rejected` are **master
 * verification** states — they describe a master's evidence review, not
 * whether the person may sign in — and they live on the `masters` profile
 * table when EPIC 5 creates it. Putting them on `users` would mean a customer
 * who never applied to be a master sits in `pending_verification` forever.
 */
export const userStatus = pgEnum('user_status', ['active', 'suspended', 'deleted']);

/**
 * The two consumer roles. **`admin` is deliberately absent**: an admin is not
 * a role on a `users` row but a separate account in `admin_users` with its own
 * credential path and no link to any consumer account
 * ([ADR-0014](docs/decisions/ADR-0014-admin-authentication.md),
 * `docs/product/user-roles.md`). Adding `'admin'` to this enum would make an
 * admin grantable to a phone-OTP account, which is exactly the structural
 * guarantee that ADR removes.
 */
export const userRole = pgEnum('user_role', ['customer', 'master']);

/**
 * Identity, and nothing else. There is no password column and there never will
 * be on this table — the consumer credential is the phone number plus an OTP
 * ([ADR-0008](docs/decisions/ADR-0008-otp-delivery.md)).
 *
 * Ids are UUIDv7 generated by the application (`common/ids/uuid-v7.ts`), so no
 * column carries a database default: PostgreSQL 17's `gen_random_uuid()` is
 * v4, and having the two generators disagree per insert path is worse than
 * having one.
 */
export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey(),

    /**
     * Normalised to E.164 before it is ever written or compared
     * (ADR-0008). Storing "+994551234567" and "0551234567" as two rows would
     * let one person hold two accounts and shed a poor rating by switching
     * between them.
     */
    phoneE164: text('phone_e164').notNull(),

    status: userStatus('status').notNull().default('active'),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),

    /**
     * Soft delete. A hard delete would orphan completed orders, payments and
     * reviews that must stay accountable (`docs/product/user-roles.md`).
     */
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (table) => [
    /**
     * Unique among LIVE accounts only, not across all rows ever written.
     *
     * A plain `UNIQUE (phone_e164)` reads stricter and is in fact wrong here:
     * users are soft-deleted, so the row survives forever, and an operator
     * reassigning a disconnected number to a new subscriber — routine in
     * Azerbaijan as everywhere — would leave that person permanently unable to
     * sign up, with no support action short of editing the database. The
     * partial index keeps ADR-0008's guarantee ("unique among verified
     * users") for every account that can actually be signed into.
     */
    uniqueIndex('users_phone_e164_live_unique')
      .on(table.phoneE164)
      .where(sql`${table.deletedAt} is null`),
  ],
);

/**
 * Role membership as a **set**, one row per role a user holds
 * (`docs/product/user-roles.md`: "Roles are a set, not a single field"). A
 * plumber with a broken fridge holds both rows on one account; a `role` column
 * on `users` would force them into two accounts and split their history,
 * reviews and phone number across both.
 *
 * This table — not the existence of a `customers` or `masters` profile row —
 * is the authority an authorization decision reads, because the guards
 * (issue #27) must answer "may this actor act as a master?" before EPIC 5
 * exists to answer it from a profile. When those profile tables land, creating
 * a profile and inserting the matching row here is one transaction; the
 * profile carries the profile data, this carries the grant.
 */
export const userRoles = pgTable(
  'user_roles',
  {
    userId: uuid('user_id')
      .notNull()
      // RESTRICT, not CASCADE: deleting a user must fail loudly rather than
      // silently shed rows (`docs/architecture/database-architecture.md`
      // § Integrity rules). Users are soft-deleted, so this never fires in
      // normal operation.
      .references(() => users.id, { onDelete: 'restrict' }),
    role: userRole('role').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.role] }),
    // The composite primary key already indexes `(user_id, role)` left-to-
    // right, which covers "every role for this user". A separate index on
    // `role` alone would only serve "every user with role X", which no query
    // in the system performs.
    index('user_roles_role_idx').on(table.role),
  ],
);

export const usersRelations = relations(users, ({ many }) => ({
  roles: many(userRoles),
}));

export const userRolesRelations = relations(userRoles, ({ one }) => ({
  user: one(users, { fields: [userRoles.userId], references: [users.id] }),
}));

export type UserRow = typeof users.$inferSelect;
export type NewUserRow = typeof users.$inferInsert;
export type UserRoleRow = typeof userRoles.$inferSelect;
export type UserRoleName = (typeof userRole.enumValues)[number];
export type UserStatusName = (typeof userStatus.enumValues)[number];
