import type { OrderActorKind, OrderStatus } from '@tezusta/types';

/** English placeholder copy for order oversight and the dispute queue (#249). */
export const ordersCopy = {
  ordersTitle: 'Orders',
  disputesTitle: 'Disputes',
  disputesIntro: 'Every disputed order, oldest first.',
  filters: 'Filters',
  statusFilter: 'Status',
  stuck: 'Stuck only',
  stuckHint: 'Accepted, on the way or arrived, and unchanged for two hours.',
  from: 'Created from',
  to: 'Created to',
  clearFilters: 'Clear filters',
  tableCaption: 'Orders',
  disputesCaption: 'Disputed orders',
  columns: {
    order: 'Order',
    status: 'Status',
    service: 'Service',
    customer: 'Customer',
    master: 'Master',
    price: 'Price',
    redispatches: 'Re-dispatches',
    created: 'Created',
    updated: 'Last change',
  },
  none: '—',
  empty: 'No orders match these filters.',
  noDisputes: 'No open disputes.',
  loading: 'Loading…',
  loadFailed: 'The list could not be loaded.',
  retry: 'Try again',
  loadMore: 'Load more',
  loadingMore: 'Loading…',

  back: 'All orders',
  orderTitle: (shortId: string) => `Order ${shortId}`,
  detailLoadFailed: 'This order could not be loaded.',
  notFound: 'There is no order with this id.',
  summary: 'Summary',
  service: 'Service',
  price: 'Price',
  priceNotSet: 'Not set yet',
  created: 'Created',
  accepted: 'Accepted',
  updated: 'Last change',
  redispatches: 'Re-dispatches',
  description: 'Problem',
  address: 'Address',
  addressParts: {
    building: 'Building',
    entrance: 'Entrance',
    floor: 'Floor',
    apartment: 'Apartment',
    landmarkNote: 'Landmark',
  },
  parties: 'Parties',
  customer: 'Customer',
  master: 'Master',
  noMaster: 'No master assigned.',
  noPhone: 'No number on file',
  revealNumber: 'Reveal number',
  revealTitle: (name: string) => `Reveal ${name}’s number`,
  revealBody:
    'The full number is shown once and the reveal is recorded with your reason in the audit log.',
  reveal: 'Reveal',
  revealing: 'Revealing…',
  revealedLabel: 'Phone number',
  close: 'Close',
  cancel: 'Cancel',
  history: 'Status history',
  noHistory: 'No status changes recorded.',
  historyEntry: (from: string, to: string) => `${from} → ${to}`,
  photos: 'Photos',
  noPhotos: 'No photos attached.',
  photo: (index: number) => `Photo ${String(index)}`,
  open: 'Open',
  opening: 'Opening…',
  openFailed: 'The photo could not be opened. Try again.',
  transcript: 'Conversation transcript',
  loadTranscript: 'Show transcript',
  transcriptHint: 'Reading the transcript is recorded in the audit log.',
  transcriptFailed: 'The transcript could not be loaded.',
  noConversations: 'No conversation took place on this order.',
  noMessages: 'No messages.',
  conversation: (index: number) => `Conversation ${String(index)}`,
  openedAt: 'Opened',
  closedAt: 'Closed',
  sender: { customer: 'Customer', master: 'Master' },

  override: 'Change status',
  overrideTitle: 'Change the order’s status',
  overrideBody:
    'Only the moves the order’s state machine allows from its current status are offered. The change and your reason are recorded in the order’s history.',
  overrideTarget: 'New status',
  overrideSubmit: 'Change status',
  overrideChoose: 'Choose a new status.',
  refundUnavailable: 'Refunds are unavailable until a payment provider is connected',
  noPermissionFor: 'Your role cannot make this change.',
  overrideDone: (status: string) => `The order is now ${status}.`,
  reasonLabel: 'Reason',
  overrideReasonHint: 'Required. Recorded in the order’s history.',
  revealReasonHint: 'Required. Recorded in the audit log.',
  reasonEmpty: 'Write a reason.',
  reasonTooLong: 'The reason must be 600 characters or fewer.',
  submitting: 'Saving…',

  errors: {
    ORDER_INVALID_TRANSITION:
      'The order can no longer make this move — its status changed. The page has been refreshed.',
    ORDER_TRANSITION_NOT_PERMITTED: 'This move is not permitted for an admin.',
    REFUND_NOT_AVAILABLE: 'Refunds are unavailable until a payment provider is connected.',
    CONFLICT: 'The order changed while you were working on it. The page has been refreshed.',
    NOT_FOUND: 'This order or person no longer exists.',
    FORBIDDEN: 'Your role does not allow this action.',
    VALIDATION_FAILED: 'The server did not accept the request. Check the reason and try again.',
    unexpected: 'Something went wrong. Try again.',
  },

  actor: {
    customer: 'the customer',
    master: 'the master',
    admin: 'an admin',
    system: 'the system',
  } satisfies Record<OrderActorKind, string>,
  by: (actor: string) => `by ${actor}`,

  status: {
    DRAFT: 'Draft',
    SEARCHING: 'Searching',
    ACCEPTED: 'Accepted',
    MASTER_ON_THE_WAY: 'On the way',
    MASTER_ARRIVED: 'Arrived',
    IN_PROGRESS: 'In progress',
    COMPLETED: 'Completed',
    PAYMENT_PENDING: 'Payment pending',
    PAID: 'Paid',
    DISPUTED: 'Disputed',
    RESOLVED: 'Resolved',
    REFUNDED: 'Refunded',
    NO_MASTER_FOUND: 'No master found',
    CANCELLED: 'Cancelled',
  } satisfies Record<OrderStatus, string>,
} as const;
