import { createHmac, randomBytes, timingSafeEqual } from 'node:crypto';

/**
 * TOTP per RFC 6238 over HOTP (RFC 4226), ADR-0043 § 2: HMAC-SHA-1, six
 * digits, a 30-second step. SHA-1 and six digits because that is what every
 * authenticator app implements; the "stronger" variants are silently
 * mis-generated by several of them, which locks the admin out rather than
 * protecting anything. HMAC-SHA-1 is not affected by SHA-1's collision
 * weakness.
 */
export const TOTP_STEP_SECONDS = 30;
export const TOTP_DIGITS = 6;
/** The current step and one either side — about ±30 s of clock drift. */
export const TOTP_WINDOW = 1;
const SECRET_BYTES = 20;

const BASE32_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';

/** RFC 4648 base32, no padding — the form authenticator apps expect. */
export function base32Encode(bytes: Buffer): string {
  let bits = 0;
  let value = 0;
  let output = '';
  for (const byte of bytes) {
    value = (value << 8) | byte;
    bits += 8;
    while (bits >= 5) {
      output += BASE32_ALPHABET[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }
  if (bits > 0) {
    output += BASE32_ALPHABET[(value << (5 - bits)) & 31];
  }
  return output;
}

export function base32Decode(text: string): Buffer {
  const clean = text.replace(/=+$/, '').replace(/\s+/g, '').toUpperCase();
  let bits = 0;
  let value = 0;
  const bytes: number[] = [];
  for (const character of clean) {
    const index = BASE32_ALPHABET.indexOf(character);
    if (index === -1) {
      throw new Error('Invalid base32 character.');
    }
    value = (value << 5) | index;
    bits += 5;
    if (bits >= 8) {
      bytes.push((value >>> (bits - 8)) & 255);
      bits -= 8;
    }
  }
  return Buffer.from(bytes);
}

export function generateTotpSecret(): Buffer {
  return randomBytes(SECRET_BYTES);
}

export function totpStepAt(now: Date): number {
  return Math.floor(now.getTime() / 1000 / TOTP_STEP_SECONDS);
}

/** HOTP(K, C) with dynamic truncation (RFC 4226 § 5.3). */
export function hotp(secret: Buffer, counter: number, digits: number = TOTP_DIGITS): string {
  const message = Buffer.alloc(8);
  message.writeBigUInt64BE(BigInt(counter));
  const digest = createHmac('sha1', secret).update(message).digest();
  const offset = (digest[digest.length - 1] ?? 0) & 0x0f;
  const binary = digest.readUInt32BE(offset) & 0x7fffffff;
  return String(binary % 10 ** digits).padStart(digits, '0');
}

/**
 * The step `code` is valid for, if any, within the window around `now` and
 * **strictly after** `lastUsedStep` — a step accepted once is never accepted
 * again, so a code read over a shoulder is dead the moment it is used.
 *
 * Every candidate step is compared, match or not, so the time taken does not
 * say which step (if any) matched.
 */
export function matchTotpStep(
  secret: Buffer,
  code: string,
  now: Date,
  lastUsedStep: number | null,
): number | undefined {
  if (!/^\d{6}$/.test(code)) {
    return undefined;
  }
  const current = totpStepAt(now);
  const given = Buffer.from(code);
  let matched: number | undefined;
  for (let step = current - TOTP_WINDOW; step <= current + TOTP_WINDOW; step += 1) {
    const expected = Buffer.from(hotp(secret, step));
    const equal = timingSafeEqual(expected, given);
    if (equal && matched === undefined && (lastUsedStep === null || step > lastUsedStep)) {
      matched = step;
    }
  }
  return matched;
}

/** The `otpauth://` URI an authenticator app scans (Key Uri Format). */
export function otpauthUri(secret: Buffer, accountName: string): string {
  const issuer = 'TezUsta';
  const label = `${encodeURIComponent(issuer)}:${encodeURIComponent(accountName)}`;
  const query = new URLSearchParams({
    secret: base32Encode(secret),
    issuer,
    algorithm: 'SHA1',
    digits: String(TOTP_DIGITS),
    period: String(TOTP_STEP_SECONDS),
  });
  return `otpauth://totp/${label}?${query.toString()}`;
}
